/**
 * Encryption of per-organization secrets (OTLP headers) with AES-256-GCM.
 *
 * The key comes from TARGET_SECRETS_KEY (64 hex chars), never from the database,
 * and is deliberately unrelated to TARGET_AUTH_SECRET. TARGET_SECRETS_KEY_PREVIOUS
 * is only used to decrypt values written before a rotation.
 *
 * Envelope: "v1:<keyId>:<iv>:<tag>:<ciphertext>" (base64url parts). The
 * organization id is bound as additional authenticated data, so a ciphertext
 * copied to another organization fails to decrypt. Fails closed without a key.
 * Nothing here logs; error messages never contain plaintext or key material.
 */
import { createCipheriv, createDecipheriv, createHash, randomBytes } from "node:crypto";
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { isLoopbackHost } from "./boot-guards.mjs";

const VERSION = "v1";
const KEY_HEX = /^[0-9a-fA-F]{64}$/;
const IV_BYTES = 12;
const TAG_BYTES = 16;
export const DEV_KEY_FILENAME = ".target-secrets.key";

export class SecretsError extends Error {
	constructor(code, message) {
		super(message ?? code);
		this.name = "SecretsError";
		this.code = code;
	}
}

/** Dev key generated by `initDevKey` (loopback binds only). */
let devKey = null;

function keyId(key) {
	return createHash("sha256").update(key).digest("hex").slice(0, 8);
}

function parseKey(hex, name) {
	if (typeof hex !== "string" || !KEY_HEX.test(hex.trim())) {
		throw new SecretsError("secrets_key_invalid", `${name} must be 64 hex characters (32 bytes)`);
	}
	return Buffer.from(hex.trim(), "hex");
}

/** Resolve `{ current, previous: [] }` from the environment (or the dev key); `current` is null when unavailable. */
function loadKeys(env = process.env) {
	const previous = [];
	if (env.TARGET_SECRETS_KEY_PREVIOUS) previous.push(parseKey(env.TARGET_SECRETS_KEY_PREVIOUS, "TARGET_SECRETS_KEY_PREVIOUS"));
	let current = null;
	if (env.TARGET_SECRETS_KEY) current = parseKey(env.TARGET_SECRETS_KEY, "TARGET_SECRETS_KEY");
	else if (devKey) current = devKey;
	return { current, previous };
}

/** True when a valid key is configured. An invalid key counts as unavailable. */
export function secretsAvailable() {
	try {
		return loadKeys().current !== null;
	} catch {
		return false;
	}
}

/**
 * Allow a generated dev key on loopback binds only. Reads the key file next to the
 * database, creating it with mode 0600 when missing. No-op when TARGET_SECRETS_KEY is set.
 * Returns true when a dev key is active.
 */
export function initDevKey({ host, dbPath, env = process.env } = {}) {
	devKey = null;
	if (env.TARGET_SECRETS_KEY) return false;
	if (!isLoopbackHost(host)) return false;
	if (!dbPath) return false;
	const file = path.join(path.dirname(path.resolve(dbPath)), DEV_KEY_FILENAME);
	if (!existsSync(file)) {
		mkdirSync(path.dirname(file), { recursive: true });
		writeFileSync(file, `${randomBytes(32).toString("hex")}\n`, { mode: 0o600, flag: "wx" });
	}
	chmodSync(file, 0o600);
	devKey = parseKey(readFileSync(file, "utf8"), "dev secrets key file");
	return true;
}

/** Forget the dev key (tests, shutdown). */
export function resetDevKey() {
	devKey = null;
}

function aad(orgId) {
	if (typeof orgId !== "string" || !orgId) throw new SecretsError("secrets_org_required", "organization id is required");
	return Buffer.from(`org:${orgId}`, "utf8");
}

export function encryptSecret(orgId, plaintext) {
	const orgAad = aad(orgId);
	if (typeof plaintext !== "string") throw new SecretsError("secrets_invalid_value", "secret must be a string");
	const { current } = loadKeys();
	if (!current) throw new SecretsError("secrets_unavailable", "TARGET_SECRETS_KEY is not configured");
	const iv = randomBytes(IV_BYTES);
	const cipher = createCipheriv("aes-256-gcm", current, iv);
	cipher.setAAD(orgAad);
	const ct = Buffer.concat([cipher.update(plaintext, "utf8"), cipher.final()]);
	const tag = cipher.getAuthTag();
	return [VERSION, keyId(current), iv.toString("base64url"), tag.toString("base64url"), ct.toString("base64url")].join(":");
}

export function decryptSecret(orgId, envelope) {
	const orgAad = aad(orgId);
	const parts = typeof envelope === "string" ? envelope.split(":") : [];
	if (parts.length !== 5 || parts[0] !== VERSION) throw new SecretsError("secrets_bad_envelope", "unrecognized secret envelope");
	const [, id, ivB64, tagB64, ctB64] = parts;
	const iv = Buffer.from(ivB64, "base64url");
	const tag = Buffer.from(tagB64, "base64url");
	if (iv.length !== IV_BYTES || tag.length !== TAG_BYTES) throw new SecretsError("secrets_bad_envelope", "unrecognized secret envelope");
	const { current, previous } = loadKeys();
	const key = [current, ...previous].find((k) => k && keyId(k) === id);
	if (!key) {
		throw new SecretsError(
			current || previous.length ? "secrets_key_mismatch" : "secrets_unavailable",
			current || previous.length ? `no configured key matches key id ${id}` : "TARGET_SECRETS_KEY is not configured",
		);
	}
	try {
		const decipher = createDecipheriv("aes-256-gcm", key, iv);
		decipher.setAAD(orgAad);
		decipher.setAuthTag(tag);
		return Buffer.concat([decipher.update(Buffer.from(ctB64, "base64url")), decipher.final()]).toString("utf8");
	} catch {
		throw new SecretsError("secrets_decrypt_failed", "secret failed authentication (tampered, or bound to another organization)");
	}
}

/** Key id the next `encryptSecret` would use, or null. Lets callers spot values to re-encrypt after rotation. */
export function currentKeyId() {
	const { current } = loadKeys();
	return current ? keyId(current) : null;
}

/** Key id recorded in an envelope, or null if it is not one. */
export function envelopeKeyId(envelope) {
	const parts = typeof envelope === "string" ? envelope.split(":") : [];
	return parts.length === 5 && parts[0] === VERSION ? parts[1] : null;
}

/** "••••" plus the last 4 characters; values of 8 chars or fewer reveal nothing. */
export function maskSecret(value) {
	if (typeof value !== "string" || value.length <= 8) return "••••";
	return `••••${value.slice(-4)}`;
}
